2024-03-24 17:25:24 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[firefox] (setup)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:*/*'
-H 'Connection:keep-alive'
-H 'Authorization:Basic OjkxOTMzNzY0NjQwMzIwMjQ4NDY=' 
-d ''
2024-03-24 17:26:00 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[firefox] (teardown)[0m
curl - X DELETE 'http://localhost:8111/app/rest/projects/id:sOjaqnsVMvt' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:5364d1c3-86f9-4217-95ba-141082f6c737'
-H 'Cookie:TCSESSIONID=43B9E8509CA068FCF04752D6DF26DBB7'
-H 'Content-Length:0'
-H 'Authorization:Basic OjkxOTMzNzY0NjQwMzIwMjQ4NDY=' 
-d '' 
 

2024-03-24 17:26:00 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:sOjaqnsVMvt'. Project cannot be found by external id 'sOjaqnsVMvt'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m