2024-03-24 17:32:46 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[webkit] (setup)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:*/*'
-H 'Connection:keep-alive'
-H 'Authorization:Basic OjU4NzM3OTU0ODMzMjQ0MDIzNTU=' 
-d ''
2024-03-24 17:33:22 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[webkit] (teardown)[0m
curl - X DELETE 'http://localhost:8111/app/rest/projects/id:OtiMfGnunI4' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:12a72814-deb8-4f77-8677-670457b3f10b'
-H 'Cookie:TCSESSIONID=F7024D917238D8F6ADD91449178CBA09'
-H 'Content-Length:0'
-H 'Authorization:Basic OjU4NzM3OTU0ODMzMjQ0MDIzNTU=' 
-d '' 
 

2024-03-24 17:33:22 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:OtiMfGnunI4'. Project cannot be found by external id 'OtiMfGnunI4'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m