2024-03-26 12:37:31 INFO [32mpytest tests/backend/test_create_project.py::TestProjectCreate::test_positive_creating_project_by_roles[By agent manager] (setup)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:*/*'
-H 'Connection:keep-alive'
-H 'Authorization:Basic OjY0NzU4MDg1MTczNDI1MzU5MjM=' 
-d ''
2024-03-26 12:37:31 INFO [32mpytest tests/backend/test_create_project.py::TestProjectCreate::test_positive_creating_project_by_roles[By agent manager] [0m
curl - X POST 'http://localhost:8111/app/rest/users' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:03470819-19c2-4864-91ce-6ff6a5376099'
-H 'Cookie:RecentLogin=; TCSESSIONID=F57E26119FB13B19F899E0FF6337A4D8'
-H 'Content-Length:142'
-H 'Authorization:Basic OjY0NzU4MDg1MTczNDI1MzU5MjM=' 
-d '{"username": "that", "password": "vs7P0ty4PbP", "email": "wburke@example.org", "roles": {"role": [{"roleId": "AGENT_MANAGER", "scope": "g"}]}}' 
 

2024-03-26 12:37:31 INFO 	RESPONSE:
STATUS_CODE: [31m400[0m
DATA: [31mResponding with error, status code: 400 (Bad Request).
Details: jetbrains.buildServer.server.rest.errors.BadRequestException: Cannot create user as user with the same username already exists, caused by: jetbrains.buildServer.users.DuplicateUserAccountException: The specified username 'that' is already in use by some other user.
Invalid request. Please check the request URL and data are correct.[0m
2024-03-26 12:37:31 INFO [32mpytest tests/backend/test_create_project.py::TestProjectCreate::test_positive_creating_project_by_roles[By agent manager] (teardown)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:03470819-19c2-4864-91ce-6ff6a5376099'
-H 'Cookie:TCSESSIONID=F57E26119FB13B19F899E0FF6337A4D8'
-H 'Authorization:Basic OjY0NzU4MDg1MTczNDI1MzU5MjM=' 
-d '' 
 

2024-03-26 12:37:31 INFO [32mpytest tests/backend/test_create_project.py::TestProjectCreate::test_positive_creating_project_by_roles[By agent manager] (teardown)[0m
curl - X DELETE 'http://localhost:8111/app/rest/projects/id:rhlXQD9C4NE' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:03470819-19c2-4864-91ce-6ff6a5376099'
-H 'Cookie:TCSESSIONID=F57E26119FB13B19F899E0FF6337A4D8'
-H 'Content-Length:0'
-H 'Authorization:Basic OjY0NzU4MDg1MTczNDI1MzU5MjM=' 
-d '' 
 

2024-03-26 12:37:31 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:rhlXQD9C4NE'. Project cannot be found by external id 'rhlXQD9C4NE'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m