2024-03-24 17:15:49 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[webkit] (setup)[0m
curl - X GET 'http://localhost:8111/authenticationTest.html?csrf' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:*/*'
-H 'Connection:keep-alive'
-H 'Authorization:Basic OjgzNzY4MDc3NzA5MDE0NDM3MzE=' 
-d ''
2024-03-24 17:16:30 INFO [32mpytest tests/frontend/test_e2e_project.py::test_e2e_create_project[webkit] (teardown)[0m
curl - X DELETE 'http://localhost:8111/app/rest/projects/id:cXgtMiQMesF' 
-H 'User-Agent:python-requests/2.31.0'
-H 'Accept-Encoding:gzip, deflate'
-H 'Accept:application/json'
-H 'Connection:keep-alive'
-H 'Content-Type:application/json'
-H 'X-TC-CSRF-Token:023e2047-2c67-415c-8238-2f6189ceca22'
-H 'Cookie:TCSESSIONID=9EF3204F7089E5548BED6D1209455987'
-H 'Content-Length:0'
-H 'Authorization:Basic OjgzNzY4MDc3NzA5MDE0NDM3MzE=' 
-d '' 
 

2024-03-24 17:16:30 INFO 	RESPONSE:
STATUS_CODE: [31m404[0m
DATA: [31mResponding with error, status code: 404 (Not Found).
Details: jetbrains.buildServer.server.rest.errors.NotFoundException: No project found by locator 'count:1,id:cXgtMiQMesF'. Project cannot be found by external id 'cXgtMiQMesF'.
Could not find the entity requested. Check the reference is correct and the user has permissions to access the entity.[0m